# docker-compose build
volumes:
  postgis-data:
    driver: local    
  cloudbeaver:
    driver: local
  geoserver-data:
    driver: local

services:
  cloudbeaver:
      image: dbeaver/cloudbeaver:latest
      environment:
        - CLOUDBEAVER_EXPIRE_SESSION_AFTER_PERIOD=1800000
      restart: on-failure
      ports:
       - '8978:8978'
      volumes:
       - cloudbeaver:/opt/cloudbeaver/workspace
  postgis:
    build:
      context: ./postgis
    user: "${UID}:${GID}"
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - ./:/data
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      POSTGRES_DB: cense
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d cense"]
      interval: 5s
      timeout: 5s
      retries: 5
  geoserver:
    build:
      context: ./geoserver
    depends_on:
      postgis:
        condition: service_healthy
    volumes:
      - geoserver-data:/opt/
    restart: always
    ports:
     - '9080:8080'
    environment:
      CORS_ENABLED: true
      GEOSERVER_DATA_DIR: /opt/geoserver_data/
      GEOSERVER_ADMIN_PASSWORD: "${GEOSERVER_ADMIN_PASSWORD}"
      GEOSERVER_ADMIN_USER: "${GEOSERVER_ADMIN_USER}"
      RUN_UNPRIVILEGED: true
      ROOT_WEBAPP_REDIRECT: true
      SKIP_DEMO_DATA: true
      GEOSERVER_CSRF_WHITELIST: cense.noise-planet.org
      PROXY_BASE_URL: https://nm.noise-planet.org/geoserver/
  webpage:
    build:
      context: ./
    ports:
      - "8080:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s


